"""Add bot notification flags to Match

Revision ID: 365a4fa68bea
Revises: 
Create Date: 2026-06-12 14:23:02.548315
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365a4fa68bea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_sent', sa.SmallInteger(), nullable=False))
        batch_op.add_column(sa.Column('result_sent', sa.SmallInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('result_sent')
        batch_op.drop_column('preview_sent')

    # ### end Alembic commands ###
